image: Visual Studio 2017

install:
  - gitversion /l console /output buildserver
  - dotnet tool install -g codecov.tool

configuration:
  - Release

build_script:
  - dotnet build

test_script:
  - dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=OpenCover /p:CoverletOutput=./Coverage.xml /p:Exclude="[xunit*]*"

after_test:
  - codecov -f .\test\ReportPortal.Client.Tests\Coverage.xml

artifacts:
  - path: '**\*.nupkg'